repos:
  - name: ft
    url: git@bitbucket.org:retailtrend/face.tracer.git
    server: dev
    branch: main

  - name: dxm
    url: git@bitbucket.org:retailtrend/cron.dxm.git
    server: dev
    branch: develop
